#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: INFO

integration:
  comfact:
    url: http://localhost:${wiremock.server.port:}
  party:
    url: http://localhost:${wiremock.server.port:}/party

spring:
  security:
    oauth2:
      client:
        provider:
          party:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          comfact:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          party:
            client-id: the-client-id
            client-secret: the-client-secret
          comfact:
            client-id: Spänks!
            client-secret: the-client-secret
