#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-comfact-facade
  security:
    oauth2:
      client:
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party
mdc:
  municipalityId:
    enabled: true

integration:
  comfact:
    connectTimeout: 5
    readTimeout: 30
  party:
    connectTimeout: 5
    readTimeout: 30

logbook:
  body-filters:
    # Exclude content from incoming requests.
    json-path:
      - key: '$..content'
        value: '[binary]'
    xPath:
      # Exclude content in traffic to/from comfact
      - key: '//*[contains(local-name(), "Content")]'
        value: '[binary]'
      # Mask password in traffic to/from comfact
      - key: '//*[contains(local-name(), "Password")]'
        value: '********'
