#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-comfact-facade
  security:
    oauth2:
      client:
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party
          comfact:
            authorization-grant-type: client_credentials
            # The token endpoint doesn't accept Basic auth with special characters in the client-id
            # Hence why we change to client_secret_post
            client-authentication-method: client_secret_post
            provider: comfact
mdc:
  municipalityId:
    enabled: true

integration:
  comfact:
    connectTimeout: 5
    readTimeout: 30
  party:
    connectTimeout: 5
    readTimeout: 30

logbook:
  body-filters:
    # Exclude content from incoming requests.
    json-path:
      - key: '$..content'
        value: '[binary]'
