#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: DEBUG

#========================================
integration:
  comfact:
    url: http://comfact.url
    username: comfact-username
    password: comfact-password
