#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: INFO

#========================================
integration:
  comfact:
    url: http://comfact.url
    username: comfact-username
    password: comfact-password
  party:
    url: http://party.url

spring:
  security:
    oauth2:
      client:
        provider:
          party:
            token-uri: http://token.url
        registration:
          party:
            client-id: the-client-id
            client-secret: the-client-secret
municipality:
  ids:
    2281:
      username: sundsvall-username
      password: sundsvall-password
    2260:
      username: ange-username
      password: ange-password