#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: DEBUG

integration:
  comfact:
    url: http://localhost:${wiremock.server.port:}/comfact
    username: comfact-username
    password: comfact-password
