#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: INFO

integration:
  comfact:
    url: http://localhost:${wiremock.server.port:}/comfact
    username: comfact-username
    password: comfact-password
  party:
    url: http://localhost:${wiremock.server.port:}/party

spring:
  security:
    oauth2:
      client:
        provider:
          party:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          party:
            client-id: the-client-id
            client-secret: the-client-secret
municipality:
  ids:
    2281:
      username: sundsvall-username
      password: sundsvall-password
    2260:
      username: ange-username
      password: ange-password