#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-comfact-facade
  security:
    oauth2:
      client:
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party

integration:
  comfact:
    connectTimeout: 5
    readTimeout: 30
  party:
    connectTimeout: 5
    readTimeout: 30

logbook:
  body-filters:
    # Exclude base64-encoded content from incoming requests.
    json-path:
      - key: '$..content'
        value: '[base64]'
    # Exclude base64-encoded content from traffic to/from skatteverket
    xPath:
      - key: '//*[contains(local-name(), "Content")]'
        value: '[base64]'
